db: &db
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: storage/<%= Rails.env %>.sqlite3

default: &default
  primary:
    <<: *db
  cache:
    <<: *db
    database: storage/<%= Rails.env %>_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *db
    database: storage/<%= Rails.env %>_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *db
    database: storage/<%= Rails.env %>_cable.sqlite3
    migrations_paths: db/cable_migrate

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default

test:
  <<: *db
